####################################################
#
# Welcome to Tfolio Jekyll Theme
#
# Product Link : https://themeix.com/product/tfolio-personal-portfolio-cv-resume-jekyll-theme/
# Version : v2.0.1
#
####################################################

title: Wontack Han
email: hanwon@iu.edu
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "personal site"
url: "http://wontackhan.me" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  wthanone

facebook_url: 'http://facebook.com/themeix'
linkedin_url: 'http://www.linkedin.com/in/wontack-han-81b8a431/'
github_url: 'http://github.com/wthanone'
#youtube_url: 'http://youtube.com/themeix'
#google_plus_url: 'http://plus.google.com'
#pinterest_url: 'http://pinterest.com'

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-seo-tag

 
