# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Wontack Han
title: Computer Science, Bioinformatics
email: hanwon@iu.edu
website: wontackhan.me

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: hanwon19
github_username:  wthanone
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: ln20180101
linkedin_username: wthanone
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/wth.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Wontack Han and I'm a Ph.D. candidate of computer science. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Research # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: comparative ananlysis of metagenome 
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
      
      - layout: top-middle
        title: machine learning 
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content: 
      - layout : left
        title : Metegenome Lab 
        sub_title : Research Assistant
        caption : 2015 - Present 
        description : |
          test

      - layout : left
        title : Bioinformatics Institute
        sub_title : Research Assistant
        caption : 2013 - 2015 
        description : |
          test

      - layout : left
        title : Somansa
        sub_title : Software Engineer
        caption : 2010 - 2012  
        description : |
          test

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content: 
      - layout : top
        title : Indiana University Bloomington
        caption : 2015 - Present 
        description : |
          Ph.D. Computer Science.

          Minor Bioinformatics.

          Supervisors: Prof. Yuzhen Ye.
      

      - layout : top
        title : Seoul National University
        caption : 2006 - 2014
        description : |
          BS Electrical and Computer Engineering.

  
  - title: Papers
    layout: text
    content: | # this will include new lines to allow paragraphs
      - [Lam, Tony J., Moses Stamboulian, **Wontack Han**, and Yuzhen Ye.  "Model-based and phylogenetically adjusted quantification of metabolic interaction between microbial species." PLoS computational biology 16.10 (2020): e1007951.](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007951&rev=1)

      - [**Wontack Han**, and Yuzhen Ye. "A repository of microbial marker genes related to human health and diseases for host phenotype prediction using microbiome data." BIOCOMPUTING 2019: Proceedings of the Pacific Symposium. 2018.](https://www.worldscientific.com/doi/abs/10.1142/9789813279827_0022)

      - [Jiao, Dazhi, **Wontack Han**, and Yuzhen Ye. "Functional association prediction by community profiling." Methods 129 (2017): 8-17.](https://www.sciencedirect.com/science/article/pii/S1046202317300270?casa_token=DON7y8IFxbcAAAAA:tiWY2HLt9g7Nm-isSCUrAfOdm5MjgpFD2uXsEiI50MXPhjJ61L-zq0W6N5MzAVc8vA8cOFQH)

      - [**Wontack Han**, Mingjie Wang, and Yuzhen Ye. "A concurrent subtractive assembly approach for identification of disease associated sub-metagenomes." International Conference on Research in Computational Molecular Biology. Springer, Cham, 2017.](https://link.springer.com/chapter/10.1007/978-3-319-56970-3_2)


  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Operating System : Linux, MacOS, Windows
      - Programming Language : C/C++, JAVA
      - Script Languague : Python, Bash, AWK
      - Mathematical Simulation : MATLAB, R
      - Parallel and GPU System : Tensorflow, OpenMP, MPI

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
