# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Wontack Han
title: Computer Science, Bioinformatics
email: hanwon@iu.edu
website: wontackhan.me

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: hanwon19
github_username:  wthanone
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: ln20180101
linkedin_username: wthanone
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/wth.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Wontack Han and I'm a Ph.D. candidate of computer science at Indiana University. My current work is the implementation of pre-assembly program using k-mers abundance information and pipeline for marker genes/genomes through machine learning algorithms. My research interests are related to comparative analysis of not only metagenome data but also human multi-omics data sets using machine learning algorithms including deep learning. Now I am looking for the job position (post-doctoral or bioinformatics research).  

  

content:
  - title: Research # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Subtractive assembly of metagenome data sets 
        link: https://sourceforge.net/projects/concurrentsa/
        # link_text: Project Website
        #additional_links:
          #- title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
          #  url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)   
        description: | # this will include new lines to allow paragraphs
          Comparative analysis of metagenomes can be used to detect sub-metagenomes(species or genesets) that are associated with specific phenotypes (e.g., host status). The typical workflow is toassemble and annotate metagenomic datasets individually or as a whole, followed by statisticaltests to identify differentially abundant species/genes. The subtractive assembly, a de novo assembly approach for comparative metagenomics, firstly detects differential reads that distinguish between two groups of metagenomes and then only assembles these reads. This approach can make the entire process for finding marker genes/genomes faster and more efficient. 

      - layout: top-middle
        title: A repository of microbial marker genes 
        link: https://sourceforge.net/projects/mi2p/
        # link_text: Project Website
        #additional_links:
          #- title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
          #  url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          The microbiome research is going through an evolutionary transition from focusing on the characterization of reference microbiomes associated with different environments/hosts to the translational applications, including using microbiome for disease diagnosis, improving the efficacy of cancer treatments, and prevention of diseases (e.g., using probiotics). Microbial markers have been identified from microbiome data derived from cohorts of patients with different diseases, treatment responsiveness, etc, and often predictors based on these markers were built for predicting host phenotype given a microbiome dataset. Unfortunately, these microbial markers and predictors are often not publishedso are not reusable by others. In this project, I report the curation of a repository of microbial marker genes and predictors built from these markers for microbiome-based prediction of host phenotype, and a computational pipeline called Mi2P (from Microbiome to Phenotype) for using the repository. 


      - layout: top-middle
        title: clustering tones of k-mers' abundance
        link: https://github.com/wthanone/kmerLSH
        # link_text: Project Website
        #additional_links:
          #- title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
          #  url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          Due to the complexity of microbial communities, the de novo partition of metagenomic space into specific biological entities remains to be difficult. To address this problem, researchers have utilized various features, including compositional features such as tetra-nucleotide statistics and coverage signals of genetic sequences. However, the assumptions of those methods are not  universally true. For example, the  methods relying on abundances of genetic sequences are admittedly weak in segregating taxonomically related organisms. In the process of exploring other features, it has been realized that utilizing co-abundance across multiple samples improves the resolution of genome segregation from metagenomic data sets. 

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content: 
      - layout : left
        title : Indiana University Bloomington 
        sub_title : Research Assistant
        caption : 2015 - Present 
        description : |
          **Metagenome Lab Prof. Yuzhen Ye**

          Working on the metagenome data analysis. 
          - Subtractive assembly for detecting biomarkers from metagenome
          - K-mers clustering using locality sensitive hashing
          - Machine learning approach for comparative metagenomic data

      - layout : left
        title : Seoul National University 
        sub_title : Research Assistant
        caption : 2013 - 2015 
        description : |
          **Bioinformatics Institute Prof. Sun Kim**

          Distinguishing cancer phenotypes by identifying differentially expressed multi-paths in signaling pathways
          - Analysis on 120 breast cancer RNA sequencing samples

      - layout : left
        title : Somansa
        sub_title : Software Engineer
        caption : 2010 - 2012  
        description : |
          QA testing for the program to monitor the leakage of personal information through the Internet. 
          - Packet analysis
          - Testing SQL database for auditing

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content: 
      - layout : top
        title : Indiana University Bloomington
        caption : 2015 - Present 
        description : |
          Ph.D. Computer Science.

          Minor Bioinformatics.

          Supervisors: Prof. Yuzhen Ye.
      

      - layout : top
        title : Seoul National University
        caption : 2006 - 2014
        description : |
          BS Electrical and Computer Engineering.

  
  - title: Papers
    layout: text
    content: | # this will include new lines to allow paragraphs
      - [Lam, Tony J., Moses Stamboulian, **Wontack Han**, and Yuzhen Ye.  "Model-based and phylogenetically adjusted quantification of metabolic interaction between microbial species." PLoS computational biology 16.10 (2020): e1007951.](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007951&rev=1)

      - [**Wontack Han**, and Yuzhen Ye. "A repository of microbial marker genes related to human health and diseases for host phenotype prediction using microbiome data." BIOCOMPUTING 2019: Proceedings of the Pacific Symposium. 2018.](https://www.worldscientific.com/doi/abs/10.1142/9789813279827_0022)

      - [Jiao, Dazhi, **Wontack Han**, and Yuzhen Ye. "Functional association prediction by community profiling." Methods 129 (2017): 8-17.](https://www.sciencedirect.com/science/article/pii/S1046202317300270?casa_token=DON7y8IFxbcAAAAA:tiWY2HLt9g7Nm-isSCUrAfOdm5MjgpFD2uXsEiI50MXPhjJ61L-zq0W6N5MzAVc8vA8cOFQH)

      - [**Wontack Han**, Mingjie Wang, and Yuzhen Ye. "A concurrent subtractive assembly approach for identification of disease associated sub-metagenomes." International Conference on Research in Computational Molecular Biology. Springer, Cham, 2017.](https://link.springer.com/chapter/10.1007/978-3-319-56970-3_2)


  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Operating System : Linux, MacOS, Windows
      - Programming Language : C/C++, JAVA
      - Script Languague : Python, Bash, AWK
      - Mathematical Simulation : MATLAB, R
      - Parallel and GPU System : Tensorflow, OpenMP, MPI
      - Database : MySQL, MSSQL

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
